### ISSUE TITLE
Gamemodes bleed into one another.

### ISSUE THREAD

**Issue by slyguy65** [Mozeman/SCPSLGamemodes#10]
Juggernaut and gangwar and zombie for sure.
If I start them, then stop them, then start a new mode and a new round, they will bleed into the next.

For example doing a zombie round, then a massacre round, will have peanuts turn dboi into zombies, which in all honesty makes the gamemode way better.

But it ruins every other gamemode.

**Comment by galaxy119** [comment]
So if you do
zombie disable
mascr enable

zombieland still is active?
