### ISSUE TITLE
How fix it 

### ISSUE THREAD

**Issue by danya201272** [Mozeman/SCPSLGamemodes#44]
I recompile your plugins and write a mistakes
![image](https://user-images.githubusercontent.com/36302863/64617423-20a37480-d3e7-11e9-84de-298683547f12.png)

**Comment by danya201272** [comment]
How fix?

**Comment by galaxy119** [comment]
Hover over the red squigglies, they will **literally** tell you what's wrong.
Make sure you have the most up to date code from the github, I have no issues in my projects currently so it must be something to do with your IDE or you haven't setup references properly.

**Comment by danya201272** [comment]
> Hover over the red squigglies, they will **literally** tell you what's wrong.
> Make sure you have the most up to date code from the github, I have no issues in my projects currently so it must be something to do with your IDE or you haven't setup references properly.

I settings references how you settings project and i download project 5hours ago.

**Comment by galaxy119** [comment]
Then it must be some issue with your IDE, because there's no issues with the project itself.

**Comment by danya201272** [comment]
> Then it must be some issue with your IDE, because there's no issues with the project itself.

I download and run project in Jetbrains Rider with ReSharper .And wrote errors the same as on visual studio with resharper

**Comment by danya201272** [comment]
Jetbrains 2019.2 and resharper 2019.2.1

**Comment by galaxy119** [comment]
I don't now what to tell you, I just made a fresh clone of the repo and it opened just fine in Jetbrains, MonoDevelop and Visual Studio
Again, hover over those red squiggly lines, and it'll literally tell you the problem and how to fix it.

**Comment by danya201272** [comment]
MonoDevelop Need to connect to visual studio?

**Comment by danya201272** [comment]
Please say all plugins connect to jetbrains

**Comment by danya201272** [comment]
What is version c# in your project?

**Comment by danya201272** [comment]
I install visual studio 2019 and write message     Error MSB3073: exit command "rm -rf Assembly* Smod* *.pdb Unity* GamemodeManager.dll" with code 9009. (1, 1)

**Comment by galaxy119** [comment]
Then remove that postbuildevent from the csproj file of the gamemodes that have it in there..
This isn't really rocket science.

**Comment by danya201272** [comment]
![image](https://user-images.githubusercontent.com/36302863/64649154-025c6980-d425-11e9-9fe6-e8a30107a065.png)
This?

**Comment by galaxy119** [comment]
just the <PostBuildEvent> line..

**Comment by danya201272** [comment]
Okey

**Comment by danya201272** [comment]
![image](https://user-images.githubusercontent.com/36302863/64650330-9af3e900-d427-11e9-8250-d213bdbd3ca2.png)
Yeah

**Comment by danya201272** [comment]
And other mistake Error CS0246: the type or namespace name 'Smod2' Could not be found (possibly missing a using Directive or Assembly reference). (6, 7)

**Comment by danya201272** [comment]
I don know how fix(((

**Comment by galaxy119** [comment]
> the type or namespace name 'Smod2' Could not be found (possibly missing a using Directive or Assembly reference)


ITS LITERALLY TELLING YOU THE PROBLEM. FIX THE REFERENCES.

If you just learned to read the errors, you'd know how to fix them. It's not very difficult, but if you cant' manage it for some reason or another, you don't really have any business building them or making edits anyways, so if you cant' figure out how to read an error and solve it ((which, i'm still unsure why you get these errors, I even loaded up an old ass laptop I never use that I've never used for programming, installed Jetbrains, clones the repo, and was immediately able to build with 0 issues), then just be patient and wait for the next release, I don't have time to baby sit you and work on things at the same time.
